#!/usr/bin/env python3
"""
Append high-confidence "missing facility" suggestions from the
verification-workflow gap analysis (/tmp/wf_results.json) into
data/canada-data.js as a new dataset block.

Each gap entry → a facility record with status mapped, capacity parsed
from approxCapacity where possible, and notes:'Added from gap review'.
"""
import json, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / 'data' / 'canada-data.js'
RESULTS = pathlib.Path('/tmp/wf_results.json')

SECTOR_MAP = {
    'Crude & Refined Oil Storage': ('Oil Storage', 'Crude Tank Farm', 'bbl'),
    'Natural Gas / LNG / NGL Storage': ('Gas Storage', 'Underground Gas Storage', 'Bcf'),
    'Grain Export & Inland Elevators': ('Agricultural Storage', 'Grain Elevator', 'tonnes'),
    'Bulk Marine Terminals': ('Bulk Commodities', 'General Bulk Terminal', 'tonnes'),
    'Container & Intermodal Terminals': ('Container & Intermodal', 'Seaport Container Terminal', 'TEU/yr'),
    'Oil Refineries & Upgraders': ('Oil Processing', 'Domestic Crude Refinery', 'kbbl/d'),
    'Petrochemical & Polymer Plants': ('Oil Processing', 'Petrochemical/Feedstock', 'kT/yr'),
    'Renewable Fuels': ('Oil Processing', 'Renewables', 'kbbl/d eq'),
    'Gas Processing & Fractionation & LNG': ('Gas Processing', 'Gas Processing Plant', 'MMcf/d'),
    'Steel & Aluminum & Base Metals': ('Metals', 'Steel', 'MTPA'),
    'Gold & Diamond & Uranium': ('Metals', 'Gold Processing Plant', 'MTPA'),
    'Pulp/Paper & Sawmills': ('Forest', 'Pulp', 'MTPA'),
    'Cement / Lime / Salt / Potash / Gypsum': ('Minerals', 'Cement', 'MTPA'),
    'Oilseed Crush & Fertilizer Production': ('Agricultural Processing', 'Oilseed', 'MTPA'),
    'Ethanol & Pulse & Feed': ('Agricultural Processing', 'Ethanol', 'MTPA'),
    'Meat / Dairy / Flour / Sugar': ('Agricultural Processing', 'Meat', 'kMT/yr'),
    'Beverage & Packaged Food & Seafood': ('Agricultural Processing', 'Seafood', 'kMT/yr'),
}

STATUS_MAP = {
    'operating': 'Active', 'active': 'Active', 'open': 'Active',
    'idle': 'Idle', 'care': 'Idle', 'mothball': 'Idle',
    'closed': 'Closed', 'shut': 'Closed', 'decommission': 'Closed',
    'construction': 'Under Construction', 'building': 'Under Construction',
    'proposed': 'Proposed', 'planned': 'Proposed', 'announced': 'Proposed',
}

# Approximate province-centroid coords (used when gap entry lacks lat/lon).
PROV_CENTROID = {
    'BC': (54.0, -125.0), 'AB': (54.0, -115.0), 'SK': (54.0, -106.0),
    'MB': (54.0, -98.0), 'ON': (50.0, -85.0), 'QC': (52.0, -72.0),
    'NB': (46.5, -66.0), 'NS': (45.0, -63.0), 'PE': (46.5, -63.5),
    'NL': (53.0, -60.0), 'YT': (63.0, -135.0), 'NT': (64.0, -120.0),
    'NU': (66.0, -95.0),
}


def parse_cap(s, default_unit):
    if not s:
        return 0, default_unit
    m = re.search(r'([\d,.]+)\s*([A-Za-z/³%]+)?', s)
    if not m:
        return 0, default_unit
    val = float(m.group(1).replace(',', ''))
    unit = (m.group(2) or default_unit).strip()
    # normalise common variants
    unit = {'kt/yr': 'kMT/yr', 'kT/yr': 'kMT/yr', 'Mt/yr': 'MTPA', 'MT/yr': 'MTPA',
            'mtpa': 'MTPA', 'bpd': 'kbbl/d', 'bbl/d': 'kbbl/d'}.get(unit, unit)
    return val, unit


def map_status(s):
    if not s:
        return 'Active'
    low = s.lower()
    for k, v in STATUS_MAP.items():
        if k in low:
            return v
    return 'Active'


def js_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def main():
    res = json.loads(RESULTS.read_text())
    src = DATA.read_text(encoding='utf-8')

    existing_names = set(re.findall(r"name:'([^']+)'", src))

    lines = ['', '// ' + '=' * 60,
             '// DATASET 5: GAP-ANALYSIS ADDITIONS (high-confidence only)',
             '// Auto-generated by scripts/append_gaps.py from review workflow.',
             '// ' + '=' * 60,
             'const gapAdditionsData = [']

    added = 0
    for g in res.get('gaps', []):
        sector_label = g.get('label', '')
        sector, subcat, dunit = SECTOR_MAP.get(sector_label, ('', '', ''))
        if not sector:
            continue
        for m in g.get('missing', []):
            if m.get('confidence') != 'high':
                continue
            name = m.get('name', '').strip()
            if not name or name in existing_names:
                continue
            prov = (m.get('province') or '').strip().upper()[:2]
            if prov not in PROV_CENTROID:
                continue
            lat, lon = PROV_CENTROID[prov]
            cap, unit = parse_cap(m.get('approxCapacity', ''), dunit)
            status = map_status(m.get('status', ''))
            why = (m.get('whyNotable', '') or '').replace('\n', ' ')
            note = f"Added from gap review · {why}"[:240]

            lines.append(
                "  {name:%s,operator:%s,sector:%s,subcategory:%s,province:%s,city:%s,"
                "lat:%.3f,lon:%.3f,capacity:%s,unit:%s,status:%s,notes:%s},"
                % (js_str(name), js_str(m.get('operator', '') or ''),
                   js_str(sector), js_str(subcat), js_str(prov),
                   js_str(m.get('city', '') or ''), lat, lon,
                   cap, js_str(unit), js_str(status), js_str(note))
            )
            existing_names.add(name)
            added += 1

    lines.append('];')
    lines.append('')

    block = '\n'.join(lines)

    if 'const gapAdditionsData' in src:
        print('! gapAdditionsData already present — skipping append (delete block to regenerate)')
        return

    # Insert before allFacilities aggregation and add to it.
    src = src.replace(
        'const allFacilities = [',
        block + '\nconst allFacilities = ['
    )
    src = src.replace(
        "  ...agriProcessingData.map(f => ({...f, dataset: 'Agricultural Processing'}))",
        "  ...agriProcessingData.map(f => ({...f, dataset: 'Agricultural Processing'})),\n"
        "  ...gapAdditionsData.map(f => ({...f, dataset: 'Gap Additions'}))"
    )
    src = src.replace(
        "    agriProcessing: agriProcessingData,\n    all: allFacilities",
        "    agriProcessing: agriProcessingData,\n    gapAdditions: gapAdditionsData,\n    all: allFacilities"
    )

    DATA.write_text(src, encoding='utf-8')
    print(f'✓ appended {added} high-confidence gap facilities to {DATA}')


if __name__ == '__main__':
    main()
